### PR TITLE
Rename strict_tls to tls_disable

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
The key vault.strict_tls was used to set the vault tls_disable configuration, which is exactle the opposite of strict tls...
I've renamed the configuration key to properly reflect its meaning.

### CODE REVIEW

**Comment by myoung34** [comment]
If y ou can get tests to pass ill look at merging

**Comment by MatthiasKuehneEllerhold** [comment]
Do you mean the travis errors?
```
Error getting repository data for epel, repository not found
 * ERROR: Failed to run install_amazon_linux_ami_stable()!!!
sh: line 149: salt-call: command not found
No salt-minion installed, install must have failed!!
```

I'm not sure if these errors because of the option renaming. I've got no experience in kitchen and barely some in ruby so I'm at loss what I'd have to do to make it work. I've search for the old config key "strict_tls" and didn't find any occurence after my changes.

So what do you need me to do to fix the tests? Are these error related to my changes at all?

**Comment by myoung34** [comment]
@MatthiasKuehneEllerhold can you rebase against master and see if the tests work for your branch as expected now?

**Comment by myoung34** [comment]
Thanks, sorry for the delay

**Pull request merged**
