### PR TITLE
Corrected version pillar. This was vault_version, should be valt:version

### PR DESCRIPTION
**Pull request by Modulus**
…is. Corrected this in the readme

### CODE REVIEW

**Comment by Modulus** [comment]
Failure in ami linux install script...

**Comment by MatthiasKuehneEllerhold** [comment]
Same error as my PRs. I'm guessing that they aren't caused by our (minor) changes.

**Comment by myoung34** [comment]
Theyre not, I havent had time to debug, but it has to do witht he version of salt installing inside the container. Ill investigate tomorrow and set aside time

**Comment by myoung34** [comment]
@Modulus can you rebase against master and see if the tests work for your branch as expected now?

**Comment by myoung34** [comment]
Thanks, sorry for the delay

**Comment by Modulus** [comment]
Sorry did not see this message before now. But it seems it worked out. Thank you :)

**Pull request merged**
