### PR TITLE
refactor(kitchen): prefer `kitchen.yml` to `.kitchen.yml`

### PR DESCRIPTION
**Pull request by myii**
* Quoting from https://kitchen.ci/docs/getting-started/kitchen-yml/:
  - As of test-kitchen 1.21.0, we now prefer `kitchen.yml` over `.kitchen.yml`.
  - This preference applies to `kitchen.local.yml` as well.
  - This is backward compatible so the dot versions continue to work.

### CODE REVIEW

**Comment by javierbertoli** [comment]
Thnaks @myii

**Comment by myii** [comment]
Thanks for the merge, @javierbertoli.

**Comment by aboe76** [comment]
@javierbertoli and @myii , I always get happy to see :tada: from semantic-release bot

**Comment by myii** [comment]
@aboe76 The message has been designed to make everyone happy!

**Pull request merged**
